#ansible-playbook test.yaml  -e "cluster_name=test.clusters.local"
- name: get service
  hosts: localhost
  gather_facts: no

#  collections:
#    - kubernetes

  tasks:
  - block:
    - name: debug vars
      vars:
        msg: |
          All vars
          {{ vars | to_nice_json }}
      debug:
        msg: "{{ msg.split('\n') }}"

    - name: test get info
      kubernetes.core.k8s_info:
        kind: Node
        namespace: default
      register: test_service

    - debug:
        var: test_service

