#ansible-playbook test.yaml  -e "cluster_name=test.clusters.local"
- name: get service
  hosts: localhost
  gather_facts: no

#  collections:
#    - kubernetes

  tasks:
  - block:
    - name: debug vars
      vars:
        msg: |
          All vars
          {{ vars | to_nice_json }}

          Host vars
          {{ hostvars | to_nice_json }}
      debug:
        msg: "{{ msg.split('\n') }}"

    - name: authenticate with hub
      kubernetes.core.k8s_auth:
        host: "https://api.{{ hub }}:6443"
        validate_certs: no
        username: "{{ user }}"
        password: "{{ pass }}"
      register: ocp_auth

    - name: test get info
      kubernetes.core.k8s_info:
        api_key: "{{ ocp_auth.k8s_auth.api_key }}"
        host: "https://api.{{ hub }}:6443"
        validate_certs: no
        kind: Node
        namespace: default
      register: test_service

    - debug:
        var: test_service

    - name: test get kube
      kubernetes.core.k8s_info:
        api_key: "{{ ocp_auth.k8s_auth.api_key }}"
        host: "https://api.{{ hub }}:6443"
        validate_certs: no
        kind: Secret
        namespace: "{{ spoke }}"
        name: "{{ spoke }}-admin-kubeconfig"
      register: test_kube

    - debug:
        var: test_kube

